// `value` is the canonical, locale-independent string stored in the database.
// `en`/`bg` are just the label shown in the dropdown for each locale.
export const BULGARIAN_CITIES = [
  { value: "Sofia", en: "Sofia", bg: "София" },
  { value: "Plovdiv", en: "Plovdiv", bg: "Пловдив" },
  { value: "Varna", en: "Varna", bg: "Варна" },
  { value: "Burgas", en: "Burgas", bg: "Бургас" },
  { value: "Ruse", en: "Ruse", bg: "Русе" },
  { value: "Stara Zagora", en: "Stara Zagora", bg: "Стара Загора" },
  { value: "Pleven", en: "Pleven", bg: "Плевен" },
  { value: "Sliven", en: "Sliven", bg: "Сливен" },
  { value: "Dobrich", en: "Dobrich", bg: "Добрич" },
  { value: "Shumen", en: "Shumen", bg: "Шумен" },
  { value: "Pernik", en: "Pernik", bg: "Перник" },
  { value: "Haskovo", en: "Haskovo", bg: "Хасково" },
  { value: "Yambol", en: "Yambol", bg: "Ямбол" },
  { value: "Pazardzhik", en: "Pazardzhik", bg: "Пазарджик" },
  { value: "Blagoevgrad", en: "Blagoevgrad", bg: "Благоевград" },
  { value: "Veliko Tarnovo", en: "Veliko Tarnovo", bg: "Велико Търново" },
  { value: "Vratsa", en: "Vratsa", bg: "Враца" },
  { value: "Gabrovo", en: "Gabrovo", bg: "Габрово" },
  { value: "Asenovgrad", en: "Asenovgrad", bg: "Асеновград" },
  { value: "Vidin", en: "Vidin", bg: "Видин" },
  { value: "Kazanlak", en: "Kazanlak", bg: "Казанлък" },
  { value: "Kyustendil", en: "Kyustendil", bg: "Кюстендил" },
  { value: "Kardzhali", en: "Kardzhali", bg: "Кърджали" },
  { value: "Montana", en: "Montana", bg: "Монтана" },
  { value: "Dimitrovgrad", en: "Dimitrovgrad", bg: "Димитровград" },
  { value: "Targovishte", en: "Targovishte", bg: "Търговище" },
  { value: "Lovech", en: "Lovech", bg: "Ловеч" },
  { value: "Silistra", en: "Silistra", bg: "Силистра" },
  { value: "Razgrad", en: "Razgrad", bg: "Разград" },
  { value: "Samokov", en: "Samokov", bg: "Самоков" },
  { value: "Sandanski", en: "Sandanski", bg: "Сандански" },
  { value: "Smolyan", en: "Smolyan", bg: "Смолян" },
];
